[log]
version = 1

[log.formatters.simple]
format = "{asctime} <{name}> [{levelname}] {message}"
datefmt = "%H:%M:%S"
style = "{"

[log.handlers.console]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "simple"

[log.handlers.file]
class = "logging.FileHandler"
filename = "hs-comment-crawler.log"
mode = "a"
encoding = "utf-8"
level = "INFO"
formatter = "simple"

[log.root]
level = "DEBUG"
handlers = ["console", "file"]